export default {
login: "dhrubajyotinath6",
id: 95700412,
node_id: "U_kgDOBbRFvA",
avatar_url: "https://avatars.githubusercontent.com/u/95700412?v=4",
gravatar_id: "",
url: "https://api.github.com/users/dhrubajyotinath6",
html_url: "https://github.com/dhrubajyotinath6",
followers_url: "https://api.github.com/users/dhrubajyotinath6/followers",
following_url: "https://api.github.com/users/dhrubajyotinath6/following{/other_user}",
gists_url: "https://api.github.com/users/dhrubajyotinath6/gists{/gist_id}",
starred_url: "https://api.github.com/users/dhrubajyotinath6/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/dhrubajyotinath6/subscriptions",
organizations_url: "https://api.github.com/users/dhrubajyotinath6/orgs",
repos_url: "https://api.github.com/users/dhrubajyotinath6/repos",
events_url: "https://api.github.com/users/dhrubajyotinath6/events{/privacy}",
received_events_url: "https://api.github.com/users/dhrubajyotinath6/received_events",
type: "User",
site_admin: false,
name: "DHRUBA JYOTI NATH",
company: null,
blog: "",
location: "INDIA",
email: null,
hireable: null,
bio: null,
twitter_username: null,
public_repos: 22,
public_gists: 1,
followers: 0,
following: 3,
created_at: "2021-12-07T14:50:40Z",
updated_at: "2022-06-03T19:21:57Z"
}
